(()=>{
const pts=[12,10,8,6,4,2,1], reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const entries=[...rows].sort((a,b)=>a.ro-b.ro), byCountry=new Map(entries.map(x=>[x.country,x]));
const q=id=>document.getElementById(id), board=q('live-scoreboard'), dName=q('delegation-name'), dStatus=q('delegation-status'), dNo=q('delegation-number'), pCount=q('replay-progress-count'), pLabel=q('replay-progress-label'), pBar=q('replay-progress-bar'), leader=q('leader-caption'), badge=q('live-badge-text'), quick=q('quick-votes-grid'), twelveQ=q('twelve-question'), twelveR=q('twelve-recipient'), intro=q('replay-intro'), overlay=q('twelve-overlay'), oGiver=q('overlay-giver'), oRec=q('overlay-recipient'), oSong=q('overlay-song'), flash=q('leader-flash'), flashCountry=q('leader-flash-country'), takeover=q('winner-takeover'), start=q('replay-start'), introStart=q('intro-start'), pause=q('replay-pause'), next=q('replay-next'), skip=q('replay-skip'), restart=q('replay-restart'), finalWrap=q('final-results');
let scores, idx=0, running=false, paused=false, token=0, tempo=.95;
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function empty(){return new Map(entries.map(x=>[x.country,{points:0,counts:Object.fromEntries(pts.map(p=>[p,0]))}]))}
function cmp(a,b){const A=scores.get(a.country),B=scores.get(b.country);if(B.points!==A.points)return B.points-A.points;for(const p of pts)if(B.counts[p]!==A.counts[p])return B.counts[p]-A.counts[p];return a.ro-b.ro}
function ranked(){return [...entries].sort(cmp)}
function row(country){return [...board.querySelectorAll('.live-row')].find(x=>x.dataset.country===country)}
function makeRows(){board.innerHTML=entries.map(x=>`<article class="live-row" data-country="${esc2(x.country)}"><div class="live-rank">${String(x.ro).padStart(2,'0')}</div><div class="live-country">${esc2(x.country)}</div><div class="live-act"><strong>${esc2(x.artist)}</strong><span>${esc2(x.song)}</span></div><div class="award-chip">+0</div><div class="live-points"><strong data-score data-value="0">0</strong><small>PUAN</small></div></article>`).join('');render()}
function count(el,to){const from=Number(el.dataset.value||el.textContent||0);el.dataset.value=to;if(reduced||from===to){el.textContent=to;return}const st=performance.now(),dur=Math.max(220,500*tempo);function t(now){const x=Math.min(1,(now-st)/dur),e=1-(1-x)**3;el.textContent=Math.round(from+(to-from)*e);if(x<1)requestAnimationFrame(t)}requestAnimationFrame(t)}
function render(country=null,award=0,twelve=false){const old=new Map();board.querySelectorAll('.live-row').forEach(r=>old.set(r.dataset.country,r.getBoundingClientRect()));const order=ranked();order.forEach((x,i)=>{const r=row(x.country);r.style.order=i;r.querySelector('.live-rank').textContent=String(i+1).padStart(2,'0');count(r.querySelector('[data-score]'),scores.get(x.country).points);r.classList.toggle('leader',i===0&&scores.get(x.country).points>0);if(x.country===country){r.classList.add('receiving');r.querySelector('.award-chip').textContent='+'+award;if(twelve)r.classList.add('twelve-hit');setTimeout(()=>r.classList.remove('receiving','twelve-hit'),Math.max(620,850*tempo))}});void board.offsetHeight;board.querySelectorAll('.live-row').forEach(r=>{const a=old.get(r.dataset.country),b=r.getBoundingClientRect();if(!a||reduced)return;const dy=a.top-b.top;if(!dy)return;r.style.transition='none';r.style.transform=`translateY(${dy}px)`;requestAnimationFrame(()=>requestAnimationFrame(()=>{r.style.transition='transform .72s cubic-bezier(.2,.8,.2,1),background .35s,border-color .35s,box-shadow .35s';r.style.transform='translateY(0)'}))});const top=order[0],n=scores.get(top.country).points;leader.textContent=n?`${top.country} · ${n} puan`:'Oylama başlamadı'}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(ms,t){let left=reduced?Math.min(ms*tempo,80):ms*tempo;while(left>0){if(t!==token)return false;if(paused){await sleep(65);continue}const s=Math.min(65,left);await sleep(s);left-=s}return t===token}
function resetQuick(){[...quick.children].forEach(x=>x.classList.remove('done'))}
function mark(p){const n=[...quick.children].find(x=>+x.textContent===+p);if(n)n.classList.add('done')}
function progress(){pCount.textContent=`${String(idx).padStart(2,'0')} / ${String(ballots.length).padStart(2,'0')}`;pBar.style.width=(idx/ballots.length*100)+'%';pLabel.textContent=idx===ballots.length?'Oylama tamamlandı':`${ballots.length-idx} delegasyon kaldı`}
function controls(){start.disabled=running&&!paused;pause.disabled=!running;pause.textContent=paused?'Devam Et':'Duraklat';next.disabled=running||idx>=ballots.length;skip.disabled=idx>=ballots.length&&!takeover.hidden}
function vote(p,c,is12=false){const s=scores.get(c);s.points+=p;s.counts[p]++;render(c,p,is12)}
async function leaderFlash(c,t){flashCountry.textContent=c;flash.hidden=false;await wait(800,t);flash.hidden=true}
async function delegation(i,t){const b=ballots[i];if(!b||t!==token)return false;const before=ranked()[0]?.country;dName.textContent=b.country;dNo.textContent=String(i+1).padStart(2,'0');dStatus.textContent='Alt puanlar scoreboard’a aktarılıyor…';badge.textContent='VOTING';resetQuick();twelveQ.textContent='?';twelveR.innerHTML='<strong>Henüz açıklanmadı</strong><span>Grand Final’ın en yüksek puanı</span>';for(const [p,c] of b.votes.filter(v=>v[0]!==12).sort((a,z)=>a[0]-z[0])){if(!(await wait(170,t)))return false;vote(p,c);mark(p);const target=byCountry.get(c);dStatus.textContent=`${p} puan · ${c} · ${target.song}`;if(!(await wait(310,t)))return false}const hit=b.votes.find(v=>v[0]===12),c=hit[1],target=byCountry.get(c);dStatus.textContent='Ve şimdi… 12 puan.';if(!(await wait(620,t)))return false;oGiver.textContent=b.country+' VERİYOR';oRec.textContent='…';oSong.textContent='12 puanın sahibi açıklanıyor';overlay.hidden=false;if(!(await wait(760,t)))return false;oRec.textContent=c;oSong.textContent=`${target.artist} · ${target.song}`;twelveQ.textContent='12';twelveR.innerHTML=`<strong>${esc2(c)}</strong><span>${esc2(target.artist)} · ${esc2(target.song)}</span>`;if(!(await wait(1080,t)))return false;overlay.hidden=true;vote(12,c,true);dStatus.textContent='12 puan · '+c;if(!(await wait(680,t)))return false;const after=ranked()[0]?.country;if(i>0&&before!==after)await leaderFlash(after,t);return t===token}
async function auto(){if(running)return;intro.classList.add('dismissed');takeover.hidden=true;finalWrap.hidden=true;running=true;paused=false;const t=token;controls();while(idx<ballots.length&&t===token){if(!(await delegation(idx,t)))break;idx++;progress();if(idx<ballots.length&&!(await wait(560,t)))break}running=false;if(t!==token)return;if(idx>=ballots.length)await finish(t);controls()}
async function manual(){if(running||idx>=ballots.length)return;intro.classList.add('dismissed');takeover.hidden=true;finalWrap.hidden=true;running=true;const t=token;controls();if(await delegation(idx,t)){idx++;progress()}running=false;if(t===token&&idx>=ballots.length)await finish(t);controls()}
function allVotes(){scores=empty();for(const b of ballots)for(const [p,c] of b.votes){const s=scores.get(c);s.points+=p;s.counts[p]++}render()}
async function finish(t=token){badge.textContent='FINAL';dName.textContent='Oylama tamamlandı';dStatus.textContent='Final scoreboard hazır.';dNo.textContent='08';progress();const w=ranked()[0];q('takeover-image').src=w.image;q('takeover-image').alt=w.artist;q('takeover-country').textContent=w.country;q('takeover-artist').textContent=w.artist;q('takeover-song').textContent='“'+w.song+'”';q('takeover-points').textContent=scores.get(w.country).points;if(!(await wait(420,t)))return;takeover.hidden=false}
function skipFinal(){token++;running=false;paused=false;intro.classList.add('dismissed');overlay.hidden=true;flash.hidden=true;allVotes();idx=ballots.length;progress();finish(token);controls()}
function reset(){token++;running=false;paused=false;idx=0;scores=empty();takeover.hidden=true;overlay.hidden=true;flash.hidden=true;finalWrap.hidden=true;intro.classList.remove('dismissed');dName.textContent='ISC 154';dNo.textContent='—';dStatus.textContent='Sekiz delegasyonun oylarını yeniden izlemeye hazırsın.';badge.textContent='READY';twelveQ.textContent='?';twelveR.innerHTML='<strong>Henüz açıklanmadı</strong><span>Grand Final’ın en yüksek puanı</span>';resetQuick();progress();render();controls()}
function showFinal(){takeover.hidden=true;finalWrap.hidden=false;setTimeout(()=>q('winner-hero').scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'}),30)}
introStart.addEventListener('click',auto);start.addEventListener('click',()=>{if(idx>=ballots.length)reset();auto()});pause.addEventListener('click',()=>{paused=!paused;controls()});next.addEventListener('click',manual);skip.addEventListener('click',skipFinal);restart.addEventListener('click',reset);q('open-final-results').addEventListener('click',showFinal);document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{tempo=Number(b.dataset.speed)||1;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b))}));
scores=empty();makeRows();progress();controls();
})();