(()=>{
const pts=[12,10,8,6,4,2,1], reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const replayEntries=[
{ro:1,country:'ROLIPEA',artist:'Lambrini Girls',song:'Cuntology 101',image:'../assets/artists/01-lambrini-girls.webp'},
{ro:2,country:'VERDE VERANO',artist:'Élise de Lune',song:'Bonne Nuit',image:'../assets/artists/02-elise-de-lune.webp'},
{ro:3,country:'GÜNEŞ DİYARI',artist:'Meira Omar & LIAMOO',song:'MAZAA',image:'../assets/artists/03-meira-omar-liamoo.png'},
{ro:4,country:'SUPERLAND',artist:'Saint Levant',song:'Nails',image:'../assets/artists/04-saint-levant.webp'},
{ro:5,country:'KIRMIZI',artist:'HAYQ',song:'Mi Patmutyun / Մի պատմություն',image:'../assets/artists/05-hayq.jpg'},
{ro:6,country:'CABURYA',artist:'Laura Pausini',song:'¿PORQUÉ TE VAS?',image:'../assets/artists/06-laura-pausini.webp'},
{ro:7,country:'STJOHN',artist:'Audrey Hobert',song:'Bowling alley',image:'../assets/artists/07-Audrey-Hobert.jpg'},
{ro:8,country:'UZANMIŞIM KUMSALA',artist:'GALENA',song:'CHATGPT',image:'../assets/artists/08-galena.jpg'}];
const replayBallots=[
{country:'ROLIPEA',votes:[[12,'VERDE VERANO'],[10,'SUPERLAND'],[8,'UZANMIŞIM KUMSALA'],[6,'GÜNEŞ DİYARI'],[4,'STJOHN'],[2,'CABURYA'],[1,'KIRMIZI']]},
{country:'VERDE VERANO',votes:[[12,'STJOHN'],[10,'UZANMIŞIM KUMSALA'],[8,'ROLIPEA'],[6,'SUPERLAND'],[4,'GÜNEŞ DİYARI'],[2,'KIRMIZI'],[1,'CABURYA']]},
{country:'GÜNEŞ DİYARI',votes:[[12,'CABURYA'],[10,'VERDE VERANO'],[8,'SUPERLAND'],[6,'STJOHN'],[4,'UZANMIŞIM KUMSALA'],[2,'ROLIPEA'],[1,'KIRMIZI']]},
{country:'SUPERLAND',votes:[[12,'UZANMIŞIM KUMSALA'],[10,'VERDE VERANO'],[8,'STJOHN'],[6,'GÜNEŞ DİYARI'],[4,'CABURYA'],[2,'ROLIPEA'],[1,'KIRMIZI']]},
{country:'KIRMIZI',votes:[[12,'ROLIPEA'],[10,'VERDE VERANO'],[8,'SUPERLAND'],[6,'STJOHN'],[4,'GÜNEŞ DİYARI'],[2,'UZANMIŞIM KUMSALA'],[1,'CABURYA']]},
{country:'CABURYA',votes:[[12,'SUPERLAND'],[10,'ROLIPEA'],[8,'GÜNEŞ DİYARI'],[6,'VERDE VERANO'],[4,'UZANMIŞIM KUMSALA'],[2,'KIRMIZI'],[1,'STJOHN']]},
{country:'STJOHN',votes:[[12,'GÜNEŞ DİYARI'],[10,'CABURYA'],[8,'UZANMIŞIM KUMSALA'],[6,'ROLIPEA'],[4,'SUPERLAND'],[2,'VERDE VERANO'],[1,'KIRMIZI']]},
{country:'UZANMIŞIM KUMSALA',votes:[[12,'CABURYA'],[10,'STJOHN'],[8,'VERDE VERANO'],[6,'SUPERLAND'],[4,'ROLIPEA'],[2,'KIRMIZI'],[1,'GÜNEŞ DİYARI']]}
];
const entries=[...replayEntries].sort((a,b)=>a.ro-b.ro),byCountry=new Map(entries.map(x=>[x.country,x]));
const q=id=>document.getElementById(id),board=q('live-scoreboard'),dName=q('delegation-name'),dStatus=q('delegation-status'),dNo=q('delegation-number'),pCount=q('replay-progress-count'),pLabel=q('replay-progress-label'),pBar=q('replay-progress-bar'),leader=q('leader-caption'),badge=q('live-badge-text'),quick=q('quick-votes-grid'),twelveQ=q('twelve-question'),twelveR=q('twelve-recipient'),intro=q('replay-intro'),overlay=q('twelve-overlay'),oGiver=q('overlay-giver'),oRec=q('overlay-recipient'),oSong=q('overlay-song'),flash=q('leader-flash'),flashCountry=q('leader-flash-country'),takeover=q('winner-takeover'),start=q('replay-start'),introStartBtn=q('intro-start'),pause=q('replay-pause'),next=q('replay-next'),skip=q('replay-skip'),restart=q('replay-restart'),finalWrap=q('final-results');
let scores,idx=0,running=false,paused=false,token=0,tempo=1;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function empty(){return new Map(entries.map(x=>[x.country,{points:0,counts:Object.fromEntries(pts.map(p=>[p,0]))}]))}
function cmp(a,b){const A=scores.get(a.country),B=scores.get(b.country);if(B.points!==A.points)return B.points-A.points;for(const p of pts)if(B.counts[p]!==A.counts[p])return B.counts[p]-A.counts[p];return a.ro-b.ro}
function ranked(){return [...entries].sort(cmp)}
function row(c){return [...board.querySelectorAll('.live-row')].find(x=>x.dataset.country===c)}
function makeRows(){board.innerHTML=entries.map(x=>`<article class="live-row" data-country="${esc(x.country)}"><div class="live-rank">${String(x.ro).padStart(2,'0')}</div><div class="live-entry"><div class="live-country">${esc(x.country)}</div><div class="live-act"><strong>${esc(x.artist)}</strong><span>${esc(x.song)}</span></div></div><div class="award-chip">+0</div><div class="live-points"><strong data-score data-value="0">0</strong><small>PUAN</small></div></article>`).join('');render()}
function count(el,to){const from=Number(el.dataset.value||el.textContent||0);el.dataset.value=String(to);if(reduced||from===to){el.textContent=String(to);return}const st=performance.now(),dur=900;function tick(now){const x=Math.min(1,(now-st)/dur),e=1-Math.pow(1-x,3);el.textContent=String(Math.round(from+(to-from)*e));if(x<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function render(country=null,award=0,is12=false){const rows=[...board.querySelectorAll('.live-row')],first=new Map(rows.map(r=>[r.dataset.country,r.getBoundingClientRect()]));const order=ranked();order.forEach((x,i)=>{const r=row(x.country);r.style.order=String(i);r.querySelector('.live-rank').textContent=String(i+1).padStart(2,'0');count(r.querySelector('[data-score]'),scores.get(x.country).points);r.classList.toggle('leader',i===0&&scores.get(x.country).points>0);if(x.country===country){r.classList.add('receiving');r.querySelector('.award-chip').textContent='+'+award;if(is12)r.classList.add('twelve-hit');setTimeout(()=>r.classList.remove('receiving','twelve-hit'),1600)}});if(!reduced){requestAnimationFrame(()=>{rows.forEach(r=>{const a=first.get(r.dataset.country),b=r.getBoundingClientRect();if(!a)return;const dx=a.left-b.left,dy=a.top-b.top;if(!dx&&!dy)return;r.animate([{transform:`translate(${dx}px,${dy}px)`,zIndex:3},{transform:'translate(0,0)',zIndex:3}],{duration:1150,easing:'cubic-bezier(.22,.78,.22,1)',fill:'none'})})})}const top=order[0],n=scores.get(top.country).points;leader.textContent=n?`${top.country} · ${n} puan`:'Oylama başlamadı'}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function wait(ms,t){let elapsed=0,total=reduced?120:ms*tempo;while(elapsed<total){if(t!==token)return false;if(paused){await sleep(80);continue}const step=Math.min(80,total-elapsed);await sleep(step);elapsed+=step}return t===token}
function resetQuick(){[...quick.children].forEach(x=>x.classList.remove('done'))}
function mark(p){const n=[...quick.children].find(x=>Number(x.textContent)===Number(p));if(n)n.classList.add('done')}
function progress(){pCount.textContent=`${String(idx).padStart(2,'0')} / ${String(replayBallots.length).padStart(2,'0')}`;pBar.style.width=(idx/replayBallots.length*100)+'%';pLabel.textContent=idx===replayBallots.length?'Oylama tamamlandı':`${replayBallots.length-idx} delegasyon kaldı`}
function controls(){start.disabled=running;pause.disabled=!running;pause.textContent=paused?'Devam Et':'Duraklat';next.disabled=running||idx>=replayBallots.length;skip.disabled=false}
function vote(p,c,is12=false){const s=scores.get(c);s.points+=p;s.counts[p]+=1;render(c,p,is12)}
async function leaderFlash(c,t){flashCountry.textContent=c;flash.hidden=false;await wait(1800,t);flash.hidden=true}
async function delegation(i,t){const b=replayBallots[i];if(!b||t!==token)return false;const before=ranked()[0]?.country;dName.textContent=b.country;dNo.textContent=String(i+1).padStart(2,'0');badge.textContent='VOTING';resetQuick();twelveQ.textContent='?';twelveR.innerHTML='<strong>Henüz açıklanmadı</strong><span>Grand Final’ın en yüksek puanı</span>';dStatus.textContent='Delegasyon bağlanıyor…';if(!(await wait(1800,t)))return false;const lower=b.votes.filter(v=>v[0]!==12).sort((a,z)=>a[0]-z[0]);dStatus.textContent='1–10 puanlar geliyor…';for(let k=0;k<lower.length;k++){const [p,c]=lower[k];vote(p,c,false);mark(p);const target=byCountry.get(c);dStatus.textContent=`${p} puan · ${c} · ${target.song}`;if(!(await wait(k===0?1900:1600,t)))return false}const hit=b.votes.find(v=>v[0]===12),c=hit[1],target=byCountry.get(c);dStatus.textContent='Ve şimdi… 12 puan.';if(!(await wait(2600,t)))return false;oGiver.textContent=b.country+' VERİYOR';oRec.textContent='…';oSong.textContent='12 puanın sahibi açıklanıyor';overlay.hidden=false;if(!(await wait(2200,t)))return false;oRec.textContent=c;oSong.textContent=`${target.artist} · ${target.song}`;twelveQ.textContent='12';twelveR.innerHTML=`<strong>${esc(c)}</strong><span>${esc(target.artist)} · ${esc(target.song)}</span>`;if(!(await wait(3000,t)))return false;overlay.hidden=true;vote(12,c,true);dStatus.textContent='12 puan · '+c;if(!(await wait(1900,t)))return false;const after=ranked()[0]?.country;if(i>0&&before!==after)await leaderFlash(after,t);return t===token}
async function auto(){if(running)return;intro.classList.add('dismissed');takeover.hidden=true;finalWrap.hidden=true;running=true;paused=false;const t=token;controls();dStatus.textContent='Oylama başlıyor…';if(!(await wait(1200,t))){running=false;controls();return}while(idx<replayBallots.length&&t===token){const ok=await delegation(idx,t);if(!ok)break;idx++;progress();if(idx<replayBallots.length){dStatus.textContent='Sıradaki delegasyona geçiliyor…';if(!(await wait(2600,t)))break}}running=false;if(t!==token)return;if(idx>=replayBallots.length)await finish(t);controls()}
async function manual(){if(running||idx>=replayBallots.length)return;intro.classList.add('dismissed');running=true;paused=false;const t=token;controls();if(await delegation(idx,t)){idx++;progress()}running=false;if(t===token&&idx>=replayBallots.length)await finish(t);controls()}
function allVotes(){scores=empty();for(const b of replayBallots)for(const [p,c] of b.votes){const s=scores.get(c);s.points+=p;s.counts[p]+=1}render()}
async function finish(t=token){badge.textContent='FINAL';dName.textContent='Oylama tamamlandı';dStatus.textContent='Final scoreboard hazır.';dNo.textContent='08';progress();const w=ranked()[0];q('takeover-image').src=w.image;q('takeover-image').alt=w.artist;q('takeover-country').textContent=w.country;q('takeover-artist').textContent=w.artist;q('takeover-song').textContent='“'+w.song+'”';q('takeover-points').textContent=String(scores.get(w.country).points);if(!(await wait(2400,t)))return;takeover.hidden=false}
function skipFinal(){token+=1;running=false;paused=false;intro.classList.add('dismissed');overlay.hidden=true;flash.hidden=true;allVotes();idx=replayBallots.length;progress();finish(token);controls()}
function reset(){token+=1;running=false;paused=false;idx=0;scores=empty();takeover.hidden=true;overlay.hidden=true;flash.hidden=true;finalWrap.hidden=true;intro.classList.remove('dismissed');dName.textContent='ISC 154';dNo.textContent='—';dStatus.textContent='Sekiz delegasyonun oylarını yeniden izlemeye hazırsın.';badge.textContent='READY';twelveQ.textContent='?';twelveR.innerHTML='<strong>Henüz açıklanmadı</strong><span>Grand Final’ın en yüksek puanı</span>';resetQuick();progress();render();controls()}
function showFinal(){takeover.hidden=true;finalWrap.hidden=false;setTimeout(()=>q('winner-hero').scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'}),30)}
introStartBtn.addEventListener('click',auto);start.addEventListener('click',auto);pause.addEventListener('click',()=>{paused=!paused;badge.textContent=paused?'PAUSED':'VOTING';dStatus.textContent=paused?'Oylama duraklatıldı.':'Oylama devam ediyor…';controls()});next.addEventListener('click',manual);skip.addEventListener('click',skipFinal);restart.addEventListener('click',reset);q('open-final-results').addEventListener('click',showFinal);document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{tempo=Number(b.dataset.speed)||1;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b))}));
scores=empty();makeRows();progress();controls();
})();